logo: /assets/avatars.png
#rss: /atom.xml
disqus:
google_analytics:

# Social accounts
instagram:
pinterest:
github: https://github.com/wincentwang
facebook: 
twitter:
linkedin:
math:
    per_page: true
    mathjax:
        enable: true
        mhchem: true